#!/bin/bash
#
# Cloud-init user data script that deploys Factry Historian on Ubuntu 24.04 LTS
# behind Caddy, which terminates TLS for the Historian web UI and Grafana.
#
# The gRPC endpoint used by remote collectors is published directly on port
# 8001; Historian terminates TLS on that port itself.

set -euo pipefail

# Git ref of this repository to take advanced/docker-compose.yml from. Pin this
# to a release tag so that every machine provisioned from this script deploys
# the same file.
COMPOSE_REF="${COMPOSE_REF:-main}"
COMPOSE_URL="https://raw.githubusercontent.com/factrylabs/historian/${COMPOSE_REF}/advanced/docker-compose.yml"

# Caddy needs a name that resolves publicly to this host to obtain a
# certificate. Only an unqualified hostname is caught here; a name that is
# qualified but private or points elsewhere still fails later, in Caddy.
# Checked before any package work so that it costs seconds, not minutes.
FQDN="$(hostname -f)"
if [[ "${FQDN}" != *.* || "${FQDN}" == localhost* ]]; then
  echo "ERROR: 'hostname -f' returned '${FQDN}', which is not a fully qualified domain name." >&2
  echo "Set the instance FQDN before running this script." >&2
  exit 1
fi

# Update system
export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY=critical
sudo -E apt-get -qy update
sudo -E apt-get -qy -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade
sudo -E apt-get -qy autoclean

# Add Docker's official GPG key:
sudo apt-get update -yq
sudo apt-get install -yq ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
  sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list

sudo apt-get update -yq

# Install Docker CE
sudo apt-get install -yq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin caddy

# Generate passwords
DB_PASSWORD="$(openssl rand -base64 32 | cut -c1-16)"
INFLUXDB_ADMIN_PASSWORD="$(openssl rand -base64 32 | cut -c1-16)"
GF_SECURITY_ADMIN_PASSWORD="$(openssl rand -base64 32 | cut -c1-16)"
# Encrypts secure settings. Losing it makes every stored collector token and
# database password unreadable, so it has to live in .env alongside the rest.
JWT_SECRET="$(openssl rand -base64 32)"

cd ~/

# The subshell keeps umask 077 local, so .env is never briefly world-readable
# and nothing later in the script inherits the restricted mask.
(
  umask 077
  cat >.env <<EOF
# Generated by user-data.sh. Keep this file; docker compose reads it on every
# invocation. Losing it makes the deployment unrecoverable.
DB_PASSWORD=${DB_PASSWORD}
INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
JWT_SECRET=${JWT_SECRET}

# Defines the project name once, so the volumes are historian_* and the
# compose commands below need no -p flag.
COMPOSE_PROJECT_NAME=historian

# Caddy terminates TLS for the web UI, so only expose the REST API on loopback.
REST_BIND_ADDRESS=127.0.0.1
GF_BIND_ADDRESS=127.0.0.1
GF_SERVER_ROOT_URL=https://${FQDN}/grafana
EOF
)

# Write caddy config
cat <<EOF | sudo tee /etc/caddy/Caddyfile
https://${FQDN} {
    # Matches both /grafana and /grafana/*. Grafana serves from the subpath
    # itself, so do not strip the prefix.
    reverse_proxy /grafana* localhost:3000

    reverse_proxy localhost:8000
}
EOF

sudo caddy validate --config /etc/caddy/Caddyfile
sudo systemctl restart caddy

curl -fsSL --retry 5 --retry-delay 3 "${COMPOSE_URL}" -o docker-compose.yml

# Fetch all four images at once, so the Grafana pull overlaps with the database
# startup and the migration instead of queueing behind them.
sudo -E docker compose pull --quiet

# AUTO_MIGRATE defaults to false, so Historian refuses to start until the schema
# is at the version its binary expects. `migrate latest` on an empty database
# creates it, and waits for PostgreSQL itself.
sudo -E docker compose run --rm migrate latest
sudo -E docker compose up -d

echo "Factry Historian is starting at https://${FQDN}"
echo "Grafana is at https://${FQDN}/grafana"
echo "Credentials are in $(pwd)/.env"
echo
echo "Caddy requests a certificate in the background. If the site does not"
echo "serve HTTPS, check that ${FQDN} resolves publicly to this host:"
echo "  journalctl -u caddy -e"
